name: Build and Push Email Worker

on:
  push:
    branches:
      - main

jobs:
  docker:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Azure-function

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/email-worker:latest \
            -f Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/email-worker:latest

      - name: Update App Service Container
        run: |
          az webapp config container set \
            --name satkon-frontend-tarckrooms \
            --resource-group satkon-prod-rg \
            --container-image-name ${{ secrets.ACR_LOGIN_SERVER }}/email-worker:latest

      - name: Restart App Service
        run: |
          az webapp restart \
            --name satkon-frontend-tarckrooms \
            --resource-group satkon-prod-rg